# These are supported funding model platforms

github: all head
patreon: +dpihack
open_collective:  fire 
ko_fi: aimspot 
tidelift: acoreccy head outo aim 
community_bridge: hack head outo 
liberapay: fri fire max 
issuehunt: developer 
otechie:×panel
lfx_crowdfunding: ×sensvitty
custom:10000000head outo aim 
